In [2]:
import numpy as np, time

In [9]:
dummy_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(f"Matrix: {dummy_matrix}") # print the matrix
print(f"Matrix Shape: {dummy_matrix.shape}")  # shape of the matrix
print(f"Number of rows: {dummy_matrix.shape[0]}")  # number of rows
print(f"Number of columns: {dummy_matrix.shape[1]}")  # number of columns
print(f"First Row: {dummy_matrix[0]}")  # access the first row
print(f"First Row: {dummy_matrix[0,:]}")  # access the first row, same as above
print(f"Frist Column: {dummy_matrix[:,0]}")  # access the first column
print(f"First row, second column element: {dummy_matrix[0,1]}")  # access the first row, second column element
print(f"Element-wise square of the matrix: {dummy_matrix**2}")  # element-wise square of the matrix


Matrix: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Matrix Shape: (4, 3)
Number of rows: 4
Number of columns: 3
First Row: [1 2 3]
First Row: [1 2 3]
Frist Column: [ 1  4  7 10]
First row, second column element: 2
Element-wise square of the matrix: [[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]


In [6]:
mu = np.mean(dummy_matrix, axis=0)  # mean of each column
print(f"mu = np.mean(dummy_matrix, axis=0) = {mu}")

max = np.max(dummy_matrix, axis=0)  # max of each column
print(f"max = np.max(dummy_matrix, axis=0) = {max}")

min = np.min(dummy_matrix, axis=0)  # min of each column
print(f"min = np.min(dummy_matrix, axis=0) = {min}")

mu = np.mean(dummy_matrix, axis=0) = [5.5 6.5 7.5]
max = np.max(dummy_matrix, axis=0) = [10 11 12]
min = np.min(dummy_matrix, axis=0) = [1 2 3]


In [ ]:
X_norm1 = (dummy_matrix - mu) / (max - min)  # normalize each column
print(f"X_norm1 = (dummy_matrix - mu) / (max - min) = \n{X_norm1}")

print(dummy_matrix[0]**2) # element-wise square of the matrix